#!/bin/sh

pinkBGStart="\033[105m\033[97m"
pinkTextStart="\033[95m"
colorEnd="\033[0m"
wpiFlag="$pinkBGStart WPI $colorEnd"
pinkHorizontal="$pinkBGStart ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ $colorEnd"
pinkHorizontalSmall="$pinkTextStart ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ $colorEnd"
pinkTick="$pinkTextStart ~ $colorEnd"

gruntModules="grunt-contrib-concat grunt-contrib-uglify grunt-contrib-watch grunt-contrib-sass grunt-autoprefixer"
wpPlugins="adminimize advanced-custom-fields force-strong-passwords"

echo "$wpiFlag Download & Extract WordPress $pinkHorizontalSmall"
curl -O http://wordpress.org/latest.tar.gz
tar -xzf latest.tar.gz
echo "$pinkTick Moving WordPress around a bit... $pinkTick"
mv wordpress/* .
rmdir wordpress/ ; rm latest.tar.gz
echo "$pinkTick Remove bullshit plugins/themes $pinkTick"
rm -rf wp-content/themes/twentythirteen wp-content/themes/twentytwelve wp-content/plugins/hello.php
echo "$pinkTick Download Underscores $pinkTick"
cd wp-content/themes
git clone https://github.com/Automattic/_s.git
rm -rf _s/.git _s/README.md
cd ../../

echo "$wpiFlag Download Underscores Add ons $pinkHorizontalSmall"
git clone git@github.com:fitzryland/WordPress-Init.git
echo "$pinkTick Moving additions to all the right places $pinkTick"
mv WordPress-Init/into-wp-root/* .
mv WordPress-Init/into-wp-root/.* .
mv WordPress-Init/into-theme-folder/* wp-content/themes/_s
rm -rf WordPress-Init
mv wp-content/themes/_s/style.css wp-content/themes/_s/sass/_base_reset.scss
# Move JS around
mkdir wp-content/themes/_s/js/lib
mv wp-content/themes/_s/js/* wp-content/themes/_s/js/lib
touch wp-content/themes/_s/js/main.js

echo "$wpiFlag Set Theme Meta $pinkHorizontalSmall"
read -p "Theme Name? " themeName
themeSlug=${PWD##*/}
read -p "Author name? " authorName
read -p "Author URI? " authorUri
read -p "Theme URI? " themeUri
read -p "Theme Version? " themeVersion
read -p "Theme Description? " themeDescription
read -p "WordPress Admin Username? " wpAdminUn
read -p "WordPress Admin Password? " wpAdminPw
read -p "WordPress Admin Email? " wpAdminEmail

echo "$pinkHorizontalSmall"
printf "Theme Name:\t\t$themeName\n"
printf "Theme Slug:\t\t$themeSlug\n"
printf "Author Name:\t\t$authorName\n"
printf "Author URI:\t\t$authorUri\n"
printf "Theme Version:\t\t$themeVersion\n"
printf "Theme Description:\t$themeDescription\n"
printf "Admin Username:\t\t$wpAdminUn\n"
printf "Admin Password:\t\t$wpAdminPw\n"
printf "Admin Email:\t\t$wpAdminEmail\n"
echo "$pinkHorizontalSmall"

echo "$wpiFlag Search & Replace underscores specific stuff in the theme code $pinkHorizontalSmall"
themeTextDomain="'$themeSlug'"
perl -pi -w -e "s/'_s'/$themeTextDomain/g;" wp-content/themes/_s/*.php
perl -pi -w -e "s/'_s'/$themeTextDomain/g;" wp-content/themes/_s/*/*.php
themeFunctionPostfix="_"
themeFunctionPrefix="$themeSlug$themeFunctionPostfix"
perl -pi -w -e "s/_s_/$themeFunctionPrefix/g;" wp-content/themes/_s/*.php
perl -pi -w -e "s/_s_/$themeFunctionPrefix/g;" wp-content/themes/_s/*/*.php
themeDocBlocks=" $themeSlug"
perl -pi -w -e "s/ _s/$themeDocBlocks/g;" wp-content/themes/_s/*.php
perl -pi -w -e "s/ _s/$themeDocBlocks/g;" wp-content/themes/_s/*/*.php
themePrefixedHandles="$themeSlug-"
perl -pi -w -e "s/_s-/$themePrefixedHandles/g;" wp-content/themes/_s/*.php
perl -pi -w -e "s/_s-/$themePrefixedHandles/g;" wp-content/themes/_s/*/*.php

echo "$pinkTick update paths for enqued scripts $pinkTick"
perl -pi -w -e "s~'/js/~'/js/lib/~g;" wp-content/themes/_s/functions.php
perl -pi -w -e "s~'/js/~'/js/lib/~g;" wp-content/themes/_s/inc/customizer.php

echo "$pinkTick Search & Replace Grunt and Compass $pinkTick"
perl -pi -w -e "s/%THEME_SLUG%/$themeSlug/g;" package.json
perl -pi -w -e "s/%THEME_SLUG%/$themeSlug/g;" Gruntfile.js
perl -pi -w -e "s/%THEME_SLUG%/$themeSlug/g;" config.rb

echo "$pinkTick Search and replace theme meta $pinkTick"
perl -pi -w -e "s~%THEME_SLUG%~$themeSlug~g;" wp-content/themes/_s/style.scss
perl -pi -w -e "s~%THEME_AUTHOR%~$authorName~g;" wp-content/themes/_s/style.scss
perl -pi -w -e "s~%THEME_AUTHOR_URI%~$authorUri~g;" wp-content/themes/_s/style.scss
perl -pi -w -e "s~%THEME_NAME%~$themeName~g;" wp-content/themes/_s/style.scss
perl -pi -w -e "s~%THEME_URI%~$themeUri~g;" wp-content/themes/_s/style.scss
perl -pi -w -e "s~%THEME_VERSION%~$themeVersion~g;" wp-content/themes/_s/style.scss
perl -pi -w -e "s~%THEME_DESCRIPTION%~$themeDescription~g;" wp-content/themes/_s/style.scss

echo "$wpiFlag Prepare For WordPress Install $pinkHorizontalSmall"

echo "$pinkTick installing Bourbon Neat $pinkTick"
cd wp-content/themes/_s/sass
git clone https://github.com/ericam/susy.git
mv susy/sass/_susy.scss .
mv susy/sass/susy/ susyTemp
rm -rf susy
mv susyTemp/ susy
cd ../../../../

echo "$pinkTick Rename _s directory $pinkTick"
themeDirectoryPath="wp-content/themes/$themeSlug"
mv wp-content/themes/_s/ $themeDirectoryPath

echo "$pinkTick Install Grunt Modules $pinkTick"
npm install $gruntModules --save-dev --quiet

echo "$pinkTick Setup wp-config $pinkTick"
mv wp-config-sample.php wp-config.php
databaseName="wpdb_$themeSlug"
perl -pi -w -e "s/database_name_here/$databaseName/g;" wp-config.php
perl -pi -w -e "s/username_here/root/g;" wp-config.php
perl -pi -w -e "s/password_here/root/g;" wp-config.php
perl -pi -w -e "s/define('WP_DEBUG', false)/define('WP_DEBUG', true)/g;" wp-config.php

echo "$pinkTick Generate Scripts & Style $pinkTick"
grunt

echo "$wpiFlag Install WordPress Database Stuff $pinkHorizontalSmall"
echo "$pinkTick Create WordPress Database $pinkTick"
/Applications/MAMP/Library/bin/mysql --verbose --user=root --password=root --execute="create database $databaseName"

echo "$pinkTick Setup WordPress Tables $pinkTick"
wp core install --url=http://localhost:8888/$themeSlug/ --title=$themeSlug --admin_user=$wpAdminUn --admin_password=$wpAdminPw --admin_email=$wpAdminEmail

echo "$wpiFlag Configure WordPress $pinkHorizontalSmall"

echo "$pinkTick Activate new theme $pinkTick"
wp theme activate $themeSlug

echo "$pinkTick Install & activate plugins $pinkTick"
wp plugin install $wpPlugins
wp plugin activate $wpPlugins

echo "$pinkTick Set permalink structure to /%postname%/ $pinkTick"
perl -pi -w -e "s~%THEME_SLUG%~$themeSlug~g;" .htaccess
wp rewrite structure '/%postname%/' --hard

echo "$pinkTick Initialize GIT $pinkTick"
git init

echo "$pinkHorizontal"
echo "$wpiFlag      All Done!     $wpiFlag"
echo "$pinkHorizontal"
echo "$wpiFlag WordPress Settings $wpiFlag"
echo "$pinkHorizontal"
printf "Theme Name:\t\t$themeName\n"
printf "Theme Slug:\t\t$themeSlug\n"
printf "Author Name:\t\t$authorName\n"
printf "Author URI:\t\t$authorUri\n"
printf "Theme Version:\t\t$themeVersion\n"
printf "Theme Description:\t$themeDescription\n"
printf "Admin Username:\t\t$wpAdminUn\n"
printf "Admin Password:\t\t$wpAdminPw\n"
printf "Admin Email:\t\t$wpAdminEmail\n"
printf "URL:\t\t\t""http://localhost:8888/$themeSlug/\n"
echo "$pinkHorizontal"
printf "Grunt Modules:\t\t$gruntModules\n"
printf "WordPress Plugins:\t$wpPlugins\n"
echo "$pinkHorizontal"