#!/bin/sh

echo "Download WordPress"
curl -O http://wordpress.org/latest.tar.gz
echo "Extracting WordPress"
tar -xvzf latest.tar.gz
echo "Moving WordPress around a bit..."
mv wordpress/* .
rmdir wordpress/ ; rm latest.tar.gz
echo "Remove bullshit plugins/themes"
echo "Remove some bullshit"
rm -rf wp-content/themes/twentythirteen wp-content/themes/twentytwelve wp-content/plugins/hello.php

echo "Download Underscores"
cd wp-content/themes
git clone https://github.com/Automattic/_s.git
rm -rf _s/.git _s/README.md
cd ../../

echo "Download Underscores Add ons"
git clone git@github.com:fitzryland/WordPress-Init.git
echo "Moving additions to all the right places"
mv WordPress-Init/into-wp-root/* .
mv WordPress-Init/into-theme-folder/* wp-content/themes/_s
rm -rf WordPress-Init
mv wp-content/themes/_s/style.css wp-content/themes/_s/sass/_base_reset.scss

echo "Set variables"
read -p "Theme Name? " themeName
echo "I will name your theme: \033[1m" $themeName "\033[0m"
themeSlug=${PWD##*/}
echo "The theme slug will be: \033[1m" $themeSlug "\033[0m this is assigned my the parent directory"
read -p "Author name? " authorName
echo "The theme slug will be: \033[1m" $authorName "\033[0m"
read -p "Author URI? " authorUri
echo "The theme slug will be: \033[1m" $authorUri "\033[0m"

read -p "Theme URI? " themeUri
echo "The theme URI will be: \033[1m" $themeUri "\033[0m"
read -p "Theme Version? " themeVersion
echo "The theme Version will be: \033[1m" $themeVersion "\033[0m"
read -p "Theme Description? " themeDescription
echo "The theme Description will be: \033[1m" $themeDescription "\033[0m"

echo "Search & Replace underscores specific stuff in the theme code"
themeTextDomain="'$themeSlug'"
perl -pi -w -e "s/'_s'/$themeTextDomain/g;" wp-content/themes/_s/*.php
perl -pi -w -e "s/'_s'/$themeTextDomain/g;" wp-content/themes/_s/*/*.php
themeFunctionPostfix="_"
themeFunctionPrefix="$themeSlug$themeFunctionPostfix"
perl -pi -w -e "s/_s_/$themeFunctionPrefix/g;" wp-content/themes/_s/*.php
perl -pi -w -e "s/_s_/$themeFunctionPrefix/g;" wp-content/themes/_s/*/*.php
themeDocBlocks=" $themeSlug"
perl -pi -w -e "s/ _s/$themeDocBlocks/g;" wp-content/themes/_s/*.php
perl -pi -w -e "s/ _s/$themeDocBlocks/g;" wp-content/themes/_s/*/*.php
themePrefixedHandles="$themeSlug-"
perl -pi -w -e "s/_s-/$themePrefixedHandles/g;" wp-content/themes/_s/*.php
perl -pi -w -e "s/_s-/$themePrefixedHandles/g;" wp-content/themes/_s/*/*.php

echo "Search & Replace Grunt stuff"
perl -pi -w -e "s/%THEME_SLUG%/$themeSlug/g;" package.json
perl -pi -w -e "s/%THEME_SLUG%/$themeSlug/g;" Gruntfile.js

echo "Search and replace theme meta"
perl -pi -w -e "s/%THEME_SLUG%/$themeSlug/g;" wp-content/themes/_s/style.scss
perl -pi -w -e "s/%THEME_AUTHOR%/$authorName/g;" wp-content/themes/_s/style.scss
perl -pi -w -e "s/%THEME_AUTHOR_URI%/$authorUri/g;" wp-content/themes/_s/style.scss
perl -pi -w -e "s/%THEME_NAME%/$themeName/g;" wp-content/themes/_s/style.scss
perl -pi -w -e "s/%THEME_URI%/$themeUri/g;" wp-content/themes/_s/style.scss
perl -pi -w -e "s/%THEME_VERSION%/$themeVersion/g;" wp-content/themes/_s/style.scss
perl -pi -w -e "s/%THEME_DESCRIPTION%/$themeDescription/g;" wp-content/themes/_s/style.scss

echo "installing Bourbon Neat"
cd wp-content/themes/_s/sass
bourbon install
neat install
cd ../../../../


echo "Rename _s directory"
themeDirectoryPath="wp-content/themes/$themeSlug"
mv wp-content/themes/_s/ $themeDirectoryPath

echo "Install Grunt Modules"
npm install grunt-contrib-concat grunt-contrib-uglify grunt-contrib-watch grunt-contrib-sass grunt-autoprefixer --save-dev

echo "setup wp-config"
mv wp-config-sample.php wp-config.php
databaseName="wpdb_$themeSlug"
perl -pi -w -e "s/database_name_here/$databaseName/g;" wp-config.php
perl -pi -w -e "s/username_here/root/g;" wp-config.php
perl -pi -w -e "s/password_here/root/g;" wp-config.php
perl -pi -w -e "s/define('WP_DEBUG', false)/define('WP_DEBUG', true)/g;" wp-config.php

echo "create database"
/Applications/MAMP/Library/bin/mysql --verbose --user=root --password=root --execute="create database $databaseName"

echo "Setup WordPress Tables - wp-cli"
read -p "WordPress Admin Username? " wpAdminUn
read -p "WordPress Admin Password? " wpAdminPw
read -p "WordPress Admin Email? " wpAdminEmail
wp core install --url=http://localhost:8888/$themeSlug/ --title=$themeSlug --admin_user=$wpAdminUn --admin_password=$wpAdminPw --admin_email=$wpAdminEmail

echo "Generate style.css"
grunt

echo "activate new theme"
wp theme activate $themeSlug

echo "install & activate plugins"
wp plugin install adminimize advanced-custom-fields force-strong-passwords
wp plugin activate adminimize advanced-custom-fields force-strong-passwords
